name: Daily Investment

on:
  workflow_dispatch:
  # schedule:
  #   - cron: '0 0 * * *' # Uncomment to run daily at midnight UTC

jobs:
  fetch_investments:
    runs-on: ubuntu-latest
    timeout-minutes: 1

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.9"

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install requests
          pip install -r Runners/investments-funds-tracker/requirements.txt

      - name: Fetch Investments
        env:
          GEMINI_KEY: ${{ secrets.GEMINI_KEY }}
          POSTGRES_URL: ${{ secrets.POSTGRES_URL }}
          REDIS_URL: ${{ secrets.REDIS_URL }}
          NEWS_KEY: ${{ secrets.NEWS_KEY }}
        run: |
          python Runners/investments-funds-tracker/run_job.py
